### ISSUE TITLE
Preprocessing msrvtt dataset

### ISSUE THREAD

**Issue by jackwu502** [YehLi/xmodaler#18]
Dear authors, I tried to use this: https://github.com/YehLi/xmodaler/blob/master/tools/msrvtt_preprocess.py to preprocess the msrvtt input json file: videodatainfo_2016.json which is given in your google drive. I expected that the output files are the same as the preprocessed msrvtt files that you put in your goole drive folder: https://drive.google.com/drive/folders/1U1692bJYZ6geqC-Kkn-TR8eBBD8tq93q. But in fact they are different in two ways. First, the output test files I preprocessed: msrvtt_caption_anno_test.pkl and captions_test_cocostyle.json are empty. Second, the size of train files and validate files I preprocessed are different from that in your google drive. For example, the msrvtt_caption_anno_train.pkl file I generated by using videodatainfo_2016.json and msrvtt_preprocess.py has length of 130260 but the preprocess msrvtt_caption_anno_train.pkl file in your google drive has length of 6513. So when I tried to run xmodaler on msrvtt dataset files preprocessed by using videodatainfo_2016.json and msrvtt_preprocess.py, I got the following error in validating:

Traceback (most recent call last):
  File "./xmodaler/train_net.py", line 68, in <module>
    args=(args,),
  File "/content/xmodaler/xmodaler/engine/launch.py", line 86, in launch
    main_func(*args)
  File "./xmodaler/train_net.py", line 56, in main
    return trainer.train()
  File "/content/xmodaler/xmodaler/engine/defaults.py", line 365, in train
    super().train(self.start_iter, self.max_iter)
  File "/content/xmodaler/xmodaler/engine/train_loop.py", line 152, in train
    self.after_step()
  File "/content/xmodaler/xmodaler/engine/train_loop.py", line 182, in after_step
    h.after_step()
  File "/content/xmodaler/xmodaler/engine/hooks.py", line 407, in after_step
    self._do_eval(epoch)
  File "/content/xmodaler/xmodaler/engine/hooks.py", line 372, in _do_eval
    results = self._func(epoch)
  File "/content/xmodaler/xmodaler/engine/defaults.py", line 328, in val_and_save_results
    eval_results = self.test(self.cfg, self.model, self.val_data_loader, self.val_evaluator, epoch)
  File "/content/xmodaler/xmodaler/engine/defaults.py", line 480, in test
    eval_res = evaluator.eval(results, epoch)
  File "/content/xmodaler/xmodaler/evaluation/coco_evaler.py", line 44, in eval
    cocoEval.evaluate()
  File "/usr/local/lib/python3.7/dist-packages/pycocoevalcap/eval.py", line 53, in evaluate
    score, scores = scorer.compute_score(gts, res)
  File "/usr/local/lib/python3.7/dist-packages/pycocoevalcap/bleu/bleu.py", line 33, in compute_score
    assert(len(hypo) == 1)
AssertionError

I guess this error arises from these two files: videodatainfo_2016.json and msrvtt_preprocess.py. I would appreciate if you can help me with this issue. Thank you very much!

**Comment by winnechan** [comment]
Thanks for reporting this issue. 
The missing test_videodatainfo_2016.json for evaluation will be uploaded to the google drive soon, and the new version of msrvtt_preprocess.py compatible with xmodaler/datasets/videos/msrvtt.py are updated.
You can pull the code and download the additional json file to run the script:
python3 msrvtt_preprocess.py --input_json videodatainfo_2016.json test_videodatainfo_2016.json --output_dir .

**Comment by jackwu502** [comment]
It works. Thank you!
