### ISSUE TITLE
TypeError: list indices must be integers or slices, not numpy.str_

### ISSUE THREAD

**Issue by chssjhjbj** [YehLi/xmodaler#43]
When training with cosnet_rl.yaml, this error occurs:
......
(predictor): BasePredictor(
    (logits): Linear(in_features=512, out_features=10200, bias=True)
    (dropout): Dropout(p=0.5, inplace=False)
  )
  (greedy_decoder): GreedyDecoder()
  (beam_searcher): BeamSearcher()
)
[09/08 16:48:14] xl.datasets.common INFO: Serializing 113287 elements to byte tensors and concatenating them all ...
[09/08 16:48:23] xl.datasets.common INFO: Serialized dataset takes 162.52 MiB
[09/08 16:48:23] xl.datasets.common INFO: Serializing 5000 elements to byte tensors and concatenating them all ...
[09/08 16:48:23] xl.datasets.common INFO: Serialized dataset takes 2.68 MiB
[09/08 16:48:23] xl.datasets.common INFO: Serializing 5000 elements to byte tensors and concatenating them all ...
[09/08 16:48:23] xl.datasets.common INFO: Serialized dataset takes 2.68 MiB
[09/08 16:48:39] fvcore.common.checkpoint INFO: [Checkpointer] Loading from /home/stormai/userfile/caoshan/code/xmodaler/ModelResult/xe/cosnet_xe.pth ...
[09/08 16:48:44] xl.engine.train_loop INFO: Starting training from iteration 0
[09/08 16:48:45] xl.engine.train_loop ERROR: Exception during training:
Traceback (most recent call last):
  File "/home/stormai/userfile/caoshan/code/xmodaler-master/xmodaler/engine/train_loop.py", line 151, in train
    self.run_step()
  File "/home/stormai/userfile/caoshan/code/xmodaler-master/xmodaler/engine/rl_mean_trainer.py", line 47, in run_step
    bs_rewards = self.scorer(bs_outputs_dict)
  File "/home/stormai/userfile/caoshan/code/xmodaler-master/xmodaler/scorer/base_scorer.py", line 66, in __call__
    gts = [self.gts[i] for i in ids]
  File "/home/stormai/userfile/caoshan/code/xmodaler-master/xmodaler/scorer/base_scorer.py", line 66, in <listcomp>
    gts = [self.gts[i] for i in ids]
TypeError: list indices must be integers or slices, not numpy.str_

I try to fix this by forcing ids and gts to convert to list, but it doesn't work. Could you pls help me ?

**Comment by YehLi** [comment]
Do you load the mscoco_train_gts.pkl correctly? The type of self.gts is dict class. The format of self.gts is:

self.gts = {
    'image_id_1': [ [word_id1, word_id2, ..., word_idn], ..., [word_id1, word_id2, ..., word_idn] ]
    'image_id_2': [ [word_id1, word_id2, ..., word_idn], ..., [word_id1, word_id2, ..., word_idn] ]
    ......
     'image_id_n': [ [word_id1, word_id2, ..., word_idn], ..., [word_id1, word_id2, ..., word_idn] ]
}

**Comment by chssjhjbj** [comment]
> Do you load the mscoco_train_gts.pkl correctly? The type of self.gts is dict class. The format of self.gts is:
> 
> self.gts = { 'image_id_1': [ [word_id1, word_id2, ..., word_idn], ..., [word_id1, word_id2, ..., word_idn] ] 'image_id_2': [ [word_id1, word_id2, ..., word_idn], ..., [word_id1, word_id2, ..., word_idn] ] ...... 'image_id_n': [ [word_id1, word_id2, ..., word_idn], ..., [word_id1, word_id2, ..., word_idn] ] }

**Comment by chssjhjbj** [comment]
Thanks for your reply. I solved this problem by  regenerating mscoco_train_gts.pkl using cider_cache.py. 
But now I have another problem. I trained CosNet with my coco_vocabulary.txt (which contained 9478 words) and got the following results: Bleu_1: 0.0004611399029899712, Bleu_2: 3.5097168050918717e-12, Bleu_3: 7.312619684285758e-15, Bleu_4: 3.516723290756723e-16, METEOR: 0.013489413339651582, ROUGE_L: 0.00043629321444025015, CIDEr: 0.0003987980550053946 and SPICE: 0.0016205068881235817. 
Even when I loaded the pre-trained model you provided and tested it directly, I got similar results: {Bleu_1': 0.0010029880686210795, 'Bleu_2': 4.837678466468649e-12, 'Bleu_3': 8.518751210209008e-15, 'Bleu_4': 3.7036076647703434e-16, 'METEOR': 0.015111546460236405, 'ROUGE_L': 0.0009796224032237032, 'CIDEr': 0.000497478889993912, 'SPICE': 0.004725523893138633}.
I don't know whether the reason is my vocabulary-size is different from yours. Could you provide your coco_vocabulary.txt  if it's convenient for you?
Or could  you provide some ideas for me to figure out?

**Comment by YehLi** [comment]
The vocabulary can be downloaded from https://drive.google.com/drive/folders/16rCskpeG5ci02YiE8uR6P8AimV6WIkcB

**Comment by chssjhjbj** [comment]
Thank you very much!
